export const RESTAURANT_LIST = [
  '3 Lopez Taqueria',
  '4 Lopez Taqueria',
  '5 Lopez Taqueria',
  '6 Lopez Taqueria',
  'A comer',
  'abc',
  'Abuelita´s',
  'Amparos restaurant',
  'Andys Taco Truck',
  'Antojitos Casa Oaxaca',
  'Antojitos Jalisco',
  'Antojitos Michalisco 1st Ave',
  'Antojitos Michalisco 72nd St',
  'Antojitos Michalisco C St',
  'Asados el catracho',
  'Ay Chabela Taqueria',
  'Baja street mexican grill',
  'Barba Azul',
  'Birrieria las Gemelas',
  'Blazing Desert Dogs',
  'Camaleon Cafe',
  'Cemitas Los Poblanos',
  'Cocina Oaxaquena',
  'Don Taco Food Cart',
  'El Agave Azul',
  'El Alteno Authentic Mexican Food',
  'El cabo restaurant',
  'El Chipotle Taqueria',
  'El Fogon Taco shop',
  'El Indio Mexicano Restaurant',
  'El negrito taqueria y antojitos mexicanos',
  'El Original Tacos El Chuy',
  'El Papas',
  'El Parrillon Loco',
  'El Pollo Rey',
  'El Pueblito Taquerias',
  'El Sazon De La Tia',
  'El sazon de mi casa',
  'El Vagoncito Chilango (South Jackson)',
  'Evil wings 1',
  'Evil wings 2',
  'Fuentes Restaurant',
  'Gaby\'s Restaurant',
  'Gorditas Nenas',
  'Gotta Getta Pizza',
  'Guanatos Mexican And Sea Food',
  'Hacienda El Rancho Viejo',
  'Jalisco Cuisine',
  'Jessies Restaurant',
  'JR Mexican Meat Market Taqueria',
  'La Barca Birria & Mariscos',
  'La Casita',
  'La Francesita Cafe y Mas by El Pueblito Taquerias',
  'La Guerrera\'s Kitchen',
  'La Huasteca Taqueria',
  'La Misma Taqueria',
  'La Perla Taco Truck',
  'La Rosita Food Truck',
  'La Salsa Mexican Food',
  'Las Doñas Mexican Food',
  'Las Esmeraldas Mexican Food',
  'Las Islitas Grill',
  'Las Islitas Mariscos',
  'Las Islitas Ostioneria',
  'Las Monas Panaderia y Pizzeria',
  'Las Poblanas Deli and Juice Bar',
  'Lily\'s Salvadorean Restaurant',
  'Lopez Taqueria',
  'Los Charritos Mexican Restaurant',
  'Los cilantros',
  'Los Cuervos',
  'Lucky Frutynnania',
  'Mar Y Sol',
  'Mariscos El Kora Restaurant',
  'Mariscos Nayarita',
  'Mexican Restaurant La Florida',
  'Micheladas Mex Grill',
  'Miches and Ceviches',
  'Mijos Taqueria',
  'Miravalle Mexican Restaurant',
  'Miriam Pupuseria and Restaurant',
  'Neveria K Botana',
  'Oyuki Sushi & Peruvian Cuisine',
  'Para y Pide',
  'Patio Tapatio',
  'Pueblo Jalisco',
  'Q rico taco',
  'Ranch Milk',
  'Ricos Nachos Mexican Grill',
  'Rock\'n Salsa Rock\'n Beer',
  'Saborcito latino Mexican Restaurant',
  'San Luis Taqueria',
  'Seaside Seafood & Market',
  'Serranos Food Truck',
  'Super Taco Taqueria Katy',
  'Ta Ricooo Mexican Food',
  'Taco Damian\'s 2 La casa del machete',
  'Taco Damian´s',
  'Taco de Mexico Casa Oaxaca',
  'Tacos A La Parrilla',
  'Tacos Acambaro',
  'Tacos al 100%',
  'Tacos Don Marcos',
  'Tacos El Gordo',
  'Tacos El Rey #2',
  'Tacos Michel',
  'Tacos y Mariscos la Gloria',
  'Taqueria Agave',
  'Taqueria Coronado',
  'Taqueria Don Chicho y Más',
  'Taqueria Dorado 2',
  'Taqueria El Jefe',
  'Taqueria El Tarasco',
  'Taqueria Familiar',
  'Taqueria Hernandez',
  'Taqueria jalapenos Y Pupuseria',
  'Taqueria Lopez 2',
  'Taqueria Los Agaves',
  'Taqueria Mi Familia',
  'Taqueria Mi Tierra II',
  'Taqueria Olgys',
  'Taqueria Rascon',
  'Taqueria Tamazula Lindo',
  'Taqueria y Pupuseria Ramos',
  'The Palm Deli',
  'Tienda y taqueria Oaxaquena',
  'Toro Viejo Taqueria',
  'Tortilla House',
  'Vagoncito Chilango (US-83 BUS)',
  'Your Taco Express',

];
